In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
data = np.array([  [1,2,3,4], [5,6,7,8],[1,4,9,6],[1,4,8,9] ]) # as it is an array we made array of array

# Standardize the data with mean 0 and std 1

In [3]:
standard_data = preprocessing.scale(data)

/home/denim/anaconda3/envs/ana41py35/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [19]:
print("\n mean of data = ",data.mean(axis= 0) )
print("\n mean of standard_data= ",standard_data.mean(axis= 0) )


 mean of data =  [2.   4.   6.75 6.75]

 mean of standard_data=  [-5.55111512e-17  0.00000000e+00  2.77555756e-17  0.00000000e+00]


In [5]:
print( "\n standard deviation = " , data.std(axis=0))
print( "\n standard deviation of standard_data = " , standard_data.std(axis=0))



 standard deviation =  [1.73205081 1.41421356 2.27760839 1.92028644]

 standard deviation of standard_data =  [1. 1. 1. 1.]


# Scale the data with to squeeze it between 0 and 1

In [6]:
data_scaling = preprocessing.MinMaxScaler(feature_range = (0,1))
scaled_data = data_scaling.fit_transform(data)

/home/denim/anaconda3/envs/ana41py35/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [7]:
print("\n scaled_data  = ", scaled_data)


 scaled_data  =  [[0.         0.         0.         0.        ]
 [1.         1.         0.66666667 0.8       ]
 [0.         0.5        1.         0.4       ]
 [0.         0.5        0.83333333 1.        ]]


# Normalize the data

In [22]:
normalized_data = preprocessing.normalize(data,norm= 'l1') # and with l2

In [23]:
print("\n normalized_data = ", normalized_data)


 normalized_data =  [[0.1        0.2        0.3        0.4       ]
 [0.19230769 0.23076923 0.26923077 0.30769231]
 [0.05       0.2        0.45       0.3       ]
 [0.04545455 0.18181818 0.36363636 0.40909091]]


# Binarization

In [10]:
binarized_data = preprocessing.binarize(data, threshold=5)  #.transform(data)

In [11]:
print("\n Binarized data = ", binarized_data)


 Binarized data =  [[0 0 0 0]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 1 1]]


In [12]:
encoder = preprocessing.OneHotEncoder()
encoder.fit([[1, 2, 1, 12], [1, 3, 5, 3], [1, 3, 2, 12], [1, 2, 4,
3]])
encoded_vector = encoder.transform([[1, 1, 1, 1]]).toarray()
print ("\nEncoded vector =", encoded_vector)



Encoded vector = [[1. 0. 0. 1. 0. 0. 0. 0. 0.]]


/home/denim/anaconda3/envs/ana41py35/lib/python3.5/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


# Label encoding 

In [13]:
input_classes = ['US', 'Russia', 'India', 'China', 'US', 'Japan', 'US', 'Ausrallia']

In [14]:
label_encoder = preprocessing.LabelEncoder()
label_encoder.fit(input_classes)
print("\nClass mapping:")
for i, item in enumerate(label_encoder.classes_):
 print(item, "-->", i)


Class mapping:
Ausrallia --> 0
China --> 1
India --> 2
Japan --> 3
Russia --> 4
US --> 5


In [15]:
# get back the value of a perticular class
labels = ['US', 'Russia', 'China']
encoded_labels = label_encoder.transform(labels)
print ("\nLabels =", labels )
print ("Encoded labels =", list(encoded_labels) )


Labels = ['US', 'Russia', 'China']
Encoded labels = [5, 4, 1]


In [16]:
encoded_labels = [2, 1, 0, 3, 1]
decoded_labels = label_encoder.inverse_transform(encoded_labels)
print ("\nEncoded labels =", encoded_labels)
print ("Decoded labels =", list(decoded_labels) )


Encoded labels = [2, 1, 0, 3, 1]
Decoded labels = ['India', 'China', 'Ausrallia', 'Japan', 'China']
